import fs from "node:fs/promises";
import path from "node:path";

const root = path.resolve(new URL("..", import.meta.url).pathname);
const file = path.join(root, "data/topics.json");
const topics = JSON.parse(await fs.readFile(file, "utf8"));

const topic = ({
  id,
  name,
  venue_name,
  city,
  district,
  players,
  duration,
  horror,
  brain,
  styles,
  source_urls,
  story_summary,
  story_summary_source_excerpt,
  rating_scope = "未採用未核實的數字評價；依官方主題資料與公開來源精選",
}) => ({
  id,
  name,
  venue_name,
  city,
  district,
  google_rating: null,
  rating_scope,
  players,
  duration,
  horror,
  brain,
  styles,
  booking_url: source_urls[0],
  source_urls,
  google_rating_scope: "未採用數字評價",
  pros: ["場景營造具沉浸感", "謎題與劇情具挑戰性"],
  cons: ["熱門時段建議提早確認"],
  data_quality: "official_topic_page_plus_public_cross_check",
  duration_source: "官方主題頁或官方預約資訊",
  editorial_scale_scope: "編輯部導覽分級；非官方難度或玩家評分",
  editorial_scale_note: "恐怖／燒腦為編輯部 1–5 導覽分級，依官方主題描述與公開主題資料整理；不代表官方標示或玩家評分。",
  story_summary,
  story_summary_provenance: "official_topic_page_plus_public_cross_check",
  story_summary_source_urls: source_urls,
  story_summary_note: "此為導覽摘要，僅依官方主題資料與公開來源整理；人數、時間與場次依官網公告。",
  story_summary_source_excerpt,
  tag_provenance: "editorial_tags_based_on_public_topic_descriptions",
  tag_provenance_note: "導覽標籤依官方主題描述與公開資料整理；不代表玩家實測心得或官方承諾。",
});

const additions = [
  topic({
    id: "popular-115",
    name: "三更",
    venue_name: "鎮冥工作室",
    city: "台中市",
    district: "大里區",
    players: "6–8",
    duration: "約150分鐘",
    horror: 5,
    brain: 3,
    styles: ["恐怖驚悚", "沉浸式演繹", "中式恐怖", "追逐體驗"],
    source_urls: ["https://escape.bar/game/26477", "https://escape.bar/firm/26465", "https://www.instagram.com/sangeng.escaqe/"],
    story_summary: "《三更》以中式恐怖與沉浸式演繹打造大型迷宮體驗，玩家在黑暗與追逐壓力中逐步完成任務。",
    story_summary_source_excerpt: "官方社群與公開主題資料將《三更》描述為大型黑追迷宮類中式沉浸式恐怖密室。",
  }),
  topic({
    id: "popular-116",
    name: "誕生",
    venue_name: "百室達密室脫逃",
    city: "台中市",
    district: "大里區",
    players: "4–8",
    duration: "約120分鐘",
    horror: 4,
    brain: 3,
    styles: ["恐怖驚悚", "泰式恐怖", "沉浸式演繹", "追逐體驗"],
    source_urls: ["https://escape.bar/game/26907", "https://escape.bar/firm/26898", "https://www.instagram.com/baishida_escape/", "https://baishidaescape.simplybook.asia/v2/"],
    story_summary: "《誕生》以泰式恐怖傳說為核心，結合沉浸演繹與追逐段落，並讓隊伍在高壓情境中完成各自任務。",
    story_summary_source_excerpt: "公開主題資料與官方社群交叉描述《誕生》為泰式恐怖、沉浸演繹與大型追逐主題。",
  }),
  topic({
    id: "popular-117",
    name: "鬼不語",
    venue_name: "山裏工作室",
    city: "台中市",
    district: "太平區",
    players: "3–6",
    duration: "約120–150分鐘",
    horror: 5,
    brain: 4,
    styles: ["恐怖驚悚", "沉浸式演繹", "高難度解謎", "單線任務"],
    source_urls: ["https://escape.bar/game/26864", "https://www.instagram.com/mountain111_escape/"],
    story_summary: "《鬼不語》以高密度題海與恐怖氛圍推進劇情，隊伍需要在單線任務節奏中協作拆解線索。",
    story_summary_source_excerpt: "公開主題資料與官方社群確認《鬼不語》為山裏工作室的恐怖密室主題，具沉浸演繹與高壓解謎特色。",
  }),
  topic({
    id: "popular-118",
    name: "LINA",
    venue_name: "梅林的鬍子遊戲工作室",
    city: "宜蘭市",
    district: "二館｜昇平街",
    players: "4–6",
    duration: "約120分鐘",
    horror: 3,
    brain: 4,
    styles: ["歐美風格", "微恐懸疑", "沉浸式演繹", "機關解謎"],
    source_urls: ["https://www.yilanmerlinsbeard.com/", "https://tinybot.cc/beardyilan/product/lina%e4%ba%8c%e9%a4%a8/?opc=1&display=1", "https://bewithnene.tw/lina/"],
    story_summary: "《LINA》是梅林二館的歐美微恐原創主題，以沉浸演繹與機關探索帶隊伍穿梭多重空間。",
    story_summary_source_excerpt: "官方網站將 LINA 標示為全新主題；公開主題資料提到微恐、NPC 與穿透式演繹。",
  }),
  topic({
    id: "popular-119",
    name: "巷仔口",
    venue_name: "梅林的鬍子遊戲工作室",
    city: "宜蘭市",
    district: "二館｜昇平街",
    players: "4–6",
    duration: "約120分鐘",
    horror: 2,
    brain: 3,
    styles: ["民國懷舊", "懸疑推理", "沉浸式演繹", "機關解謎"],
    source_urls: ["https://www.yilanmerlinsbeard.com/", "https://beardyilan.com/alley/", "https://escape.bar/game/17377", "https://bewithnene.tw/alley-entrance/"],
    story_summary: "《巷仔口》以宜蘭街景與民國懷舊氛圍包裹推理解謎，適合喜歡場景細節與故事探索的隊伍。",
    story_summary_source_excerpt: "官方頁面將巷仔口列為二館主題；公開主題資料描述其為懷舊風格與推理解謎作品。",
    rating_scope: "EscapeBar 公開主題評價與官方原創主題資料；本站不將其轉作店家評分",
  }),
  topic({
    id: "popular-120",
    name: "陰緣",
    venue_name: "梅林的鬍子遊戲工作室",
    city: "宜蘭市",
    district: "本館｜康樂路",
    players: "4–8",
    duration: "約120分鐘",
    horror: 4,
    brain: 3,
    styles: ["恐怖驚悚", "台灣民俗", "沉浸式演繹", "角色扮演"],
    source_urls: ["https://www.yilanmerlinsbeard.com/", "https://beardyilan.com/ghostmarriage/", "https://bewithnene.tw/yilanmerlinsbeard-ghostmarriage/"],
    story_summary: "《陰緣》以台灣民俗與角色扮演營造恐怖沉浸感，讓隊伍在故事與任務交錯中追查陰影裡的線索。",
    story_summary_source_excerpt: "官方網站列出陰緣為梅林主題；公開主題資料將其描述為恐怖、民俗與沉浸演繹作品。",
  }),
  topic({
    id: "popular-121",
    name: "花見小路",
    venue_name: "梅林的鬍子遊戲工作室",
    city: "宜蘭市",
    district: "本館｜康樂路",
    players: "3–5",
    duration: "約60–90分鐘",
    horror: 1,
    brain: 3,
    styles: ["日式風格", "新手小品", "解謎探索", "機關解謎"],
    source_urls: ["https://www.yilanmerlinsbeard.com/", "https://beardyilan.com/flower/", "https://bewithnene.tw/hanamikoji/"],
    story_summary: "《花見小路》以日式唯美場景承載精緻小品解謎，適合想從較輕盈節奏開始探索宜蘭密室的玩家。",
    story_summary_source_excerpt: "官方網站列出花見小路為本館主題；公開主題資料描述其為日式唯美小品，最低 3 人可玩。",
  }),
  topic({
    id: "popular-122",
    name: "聖劍騎士",
    venue_name: "梅林的鬍子遊戲工作室",
    city: "宜蘭市",
    district: "本館｜康樂路",
    players: "6–10",
    duration: "約90分鐘",
    horror: 1,
    brain: 3,
    styles: ["奇幻冒險", "角色扮演", "多人協作", "機關解謎"],
    source_urls: ["https://www.yilanmerlinsbeard.com/", "https://beardyilan.com/sword/", "https://roger5050.pixnet.net/blog/posts/15176346795"],
    story_summary: "《聖劍騎士》以奇幻冒險與多人角色扮演串起機關解謎，適合團體一起投入任務與故事。",
    story_summary_source_excerpt: "官方網站列出聖劍騎士為本館主題；公開主題資料描述其為奇幻冒險與多人團體向作品。",
  }),
  topic({
    id: "popular-123",
    name: "荒村小學",
    venue_name: "塊陶阿工作室",
    city: "桃園市",
    district: "中壢店",
    players: "4–9",
    duration: "90分鐘",
    horror: 4,
    brain: 3,
    styles: ["校園怪談", "驚悚恐怖", "NPC互動", "追逐體驗"],
    source_urls: ["https://www.kuaitaoa.cc/", "https://www.kuaitaoa.cc/荒村小學/"],
    story_summary: "《荒村小學》是塊陶阿桃園中壢店的校園怪談主題，以驚悚場景與互動演出帶隊伍找出荒村校舍的秘密。",
    story_summary_source_excerpt: "官方首頁將荒村小學列為桃園中壢店主題，並明示 90 分鐘、4–9 人。",
  }),
  topic({
    id: "popular-124",
    name: "見鬼十法",
    venue_name: "塊陶阿工作室",
    city: "台北市",
    district: "晴光店｜中山",
    players: "4–8",
    duration: "90分鐘",
    horror: 4,
    brain: 3,
    styles: ["試膽體驗", "驚悚恐怖", "NPC互動", "單線任務"],
    source_urls: ["https://www.kuaitaoa.cc/", "https://www.kuaitaoa.cc/見鬼十法/"],
    story_summary: "《見鬼十法》是塊陶阿晴光店的驚悚主題，以試膽與互動演出推進一段高壓單線任務。",
    story_summary_source_excerpt: "官方首頁將見鬼十法列為台北晴光店主題，並明示 90 分鐘、4–8 人；本筆不歸入桃園。",
  }),
];

const existingKeys = new Set(topics.map((item) => `${item.venue_name}::${item.name}`));
const next = [...topics];
for (const item of additions) {
  const key = `${item.venue_name}::${item.name}`;
  if (!existingKeys.has(key)) {
    next.push(item);
    existingKeys.add(key);
  }
}

await fs.writeFile(file, `${JSON.stringify(next, null, 2)}\n`, "utf8");
console.log(JSON.stringify({ before: topics.length, candidates: additions.length, after: next.length, added: next.length - topics.length }, null, 2));
